app_id: YOUR_APP_ID
app_secret: YOUR_APP_SECRET
redirect: http://localhost:8000/microsoft_auth/callback
scopes: openid profile offline_access user.read calendars.read
authority: https://login.microsoftonline.com/common
authorize_endpoint: /oauth2/v2.0/authorize
token_endpoint: /oauth2/v2.0/token